stages:
  - check
  - build
  - lint
  - test
  - deploy

variables:
  PROJECT_PATH: /app
  BUILD_TYPE: Release
  BUILD_PATH: ${PROJECT_PATH}/_build
  CPP_SRC_FILES: $(find ${PROJECT_PATH} -regex '.*\.\(cpp\|hpp\)')
  CXX: g++
  MAX_CODE_QUALITY_ISSUE_PER_FILE: 20

cache:
  # Enable per-branch caching
  key: $CI_COMMIT_REF_SLUG
  paths:
    - $PROJECT_PATH

clang_check:
  stage: check
  image: registry.gitlab.laneuville.me/rom1/poker-bot/builder-linux-clang:latest
  script:
    # Download the source code once for all the jobs using cache
    - git clone $CI_REPOSITORY_URL /app
    - clang-check -analyze -p $BUILD_PATH -extra-arg=-std=c++20 $CPP_SRC_FILES -o clang-check-report.plist --
  artifacts:
    reports:
      codequality: clang-check-report.plist

build_linux:
  stage: build
  image: registry.gitlab.laneuville.me/rom1/poker-bot/builder-linux-gcc:latest
  script:
    - cmake -H $PROJECT_PATH -B $BUILD_PATH -DCMAKE_BUILD_TYPE=$BUILD_TYPE && cmake --build $BUILD_PATH
  artifacts:
    paths:
      - $BUILD_PATH
  only:
    - main
    - release/*
  variables:
    BUILD_TYPE: Release
  dependencies:
    - check

build_linux_debug:
  stage: build
  image: registry.gitlab.laneuville.me/rom1/poker-bot/builder-linux-gcc-dev:latest
  script:
    - cmake -H $PROJECT_PATH -B $BUILD_PATH -DCMAKE_BUILD_TYPE=$BUILD_TYPE && cmake --build $BUILD_PATH
  artifacts:
    paths:
      - $BUILD_PATH
  except:
    - main
    - release/*
  variables:
    BUILD_TYPE: Debug
  dependencies:
    - check

build_windows:
  stage: build
  image: registry.gitlab.laneuville.me/rom1/poker-bot/builder-windows-mingw:latest
  script:
    - cmake -H $PROJECT_PATH -B $BUILD_PATH -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_SYSTEM_NAME=Windows && cmake --build $BUILD_PATH
  artifacts:
    paths:
      - '*.exe'
  only:
    - main
  dependencies:
    - check

clang_format:
  stage: lint
  image: registry.gitlab.laneuville.me/rom1/poker-bot/builder-linux-clang:latest
  script:
    - clang-format --Werror --Wclang-format-violations --dry-run $CPP_SRC_FILES
  dependencies:
    - check

clang_tidy:
  stage: lint
  image: registry.gitlab.laneuville.me/rom1/poker-bot/builder-linux-clang:latest
  script:
    - clang-tidy -checks='*' -warnings-as-errors='*,-*,<file-number>>$MAX_CODE_QUALITY_ISSUE_PER_FILE' \
      -p $BUILD_PATH -extra-arg=-std=c++20 -export-fixes=clang-tidy-report.yaml $CPP_SRC_FILES --
  artifacts:
    reports:
      codequality: clang-tidy-report.yaml
  dependencies:
    - check

test:
  stage: test
  image: registry.gitlab.laneuville.me/rom1/poker-bot/builder-linux-clang:latest
  script:
    - cmake --build $BUILD_PATH --target test
    - $BUILD_PATH/test
  dependencies:
    - build

deploy:
  stage: deploy
  image: registry.gitlab.laneuville.me/rom1/poker-bot/deploy:latest
  script:
    - echo "Creating release"
    - gitlab-artifacts download build_windows build_linux
    # todo version.txt
    - git tag $CI_COMMIT_TAG
    - git push --tags
  only:
    - main
  dependencies:
    - test
