services:

  # ----------------------------------------------------- Builders -----------------------------------------------------

  builder-linux-gcc:
    build:
      context: .
      dockerfile: docker/Dockerfile-builder-linux-gcc
      args:
        - GCC_VERSION=${GCC_VERSION}
        - CMAKE_VERSION=${CMAKE_VERSION}
        - SDL_VERSION=${SDL_VERSION}
        - LEPTONICA_VERSION=${LEPTONICA_VERSION}
        - TESSERACT_VERSION=${TESSERACT_VERSION}
        - OPENCV_VERSION=${OPENCV_VERSION}
        - NLOHMANN_JSON_VERSION=${NLOHMANN_JSON_VERSION}
        - QUILL_VERSION=${QUILL_VERSION}
        - GOOGLETEST_VERSION=${GOOGLETEST_VERSION}
        - MAX_CPU_CORES=${MAX_CPU_CORES}
    image: ${REGISTRY_HOST}/${REGISTRY_REPO_PATH}/builder-linux-gcc:latest

  builder-linux-clang:
    build:
      context: .
      dockerfile: docker/Dockerfile-builder-linux-clang
      args:
        - CI_REGISTRY=${REGISTRY_HOST}
        - CI_REGISTRY_BUILDER_ROOT_IMAGE=${REGISTRY_REPO_PATH}/builder-linux-gcc
        - CLANG_VERSION=${CLANG_VERSION}
        - MAX_CPU_CORES=${MAX_CPU_CORES}
    image: ${REGISTRY_HOST}/${REGISTRY_REPO_PATH}/builder-linux-clang:latest

  builder-linux-clang-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile-builder-linux-clang-dev
      args:
        - CI_REGISTRY=${REGISTRY_HOST}
        - CI_REGISTRY_BUILDER_ROOT_IMAGE=${REGISTRY_REPO_PATH}/builder-linux-clang
        - GDB_VERSION=${GDB_VERSION}
        - MAX_CPU_CORES=${MAX_CPU_CORES}
    image: ${REGISTRY_HOST}/${REGISTRY_REPO_PATH}/builder-linux-clang-dev:latest

  builder-linux-clang-ci:
    build:
      context: .
      dockerfile: docker/Dockerfile-builder-linux-clang-ci
      args:
        - CI_REGISTRY=${REGISTRY_HOST}
        - CI_REGISTRY_BUILDER_ROOT_IMAGE=${REGISTRY_REPO_PATH}/builder-linux-clang
        - CPP_CHECK_VERSION=${CPP_CHECK_VERSION}
        - CODE_CHECKER_VERSION=${CODE_CHECKER_VERSION}
        - MAX_CPU_CORES=${MAX_CPU_CORES}
    image: ${REGISTRY_HOST}/${REGISTRY_REPO_PATH}/builder-linux-clang-ci:latest

  builder-windows-mingw:
    build:
      context: .
      dockerfile: docker/Dockerfile-builder-windows-mingw
      args:
        - MINGW_VERSION=${MINGW_VERSION}
        - CMAKE_VERSION=${CMAKE_VERSION}
        - PKG_CONFIG_VERSION=${PKG_CONFIG_VERSION}
        - BINUTILS_VERSION=${BINUTILS_VERSION}
        - GCC_VERSION=${GCC_VERSION}
        - SDL_VERSION=${SDL_VERSION}
        - LEPTONICA_VERSION=${LEPTONICA_VERSION}
        - TESSERACT_VERSION=${TESSERACT_VERSION}
        - OPENCV_VERSION=${OPENCV_VERSION}
        - NLOHMANN_JSON_VERSION=${NLOHMANN_JSON_VERSION}
        - QUILL_VERSION=${QUILL_VERSION}
        - GOOGLETEST_VERSION=${GOOGLETEST_VERSION}
        - MAX_CPU_CORES=${MAX_CPU_CORES}
    image: ${REGISTRY_HOST}/${REGISTRY_REPO_PATH}/builder-windows-mingw:latest

  builder-windows-mingw-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile-builder-windows-mingw-dev
      args:
        - CI_REGISTRY=${REGISTRY_HOST}
        - CI_REGISTRY_BUILDER_ROOT_IMAGE=${REGISTRY_REPO_PATH}/builder-windows-mingw
    image: ${REGISTRY_HOST}/${REGISTRY_REPO_PATH}/builder-windows-mingw-dev:latest

  deploy:
    build:
      context: .
      dockerfile: docker/Dockerfile-deploy
    image: ${REGISTRY_HOST}/${REGISTRY_REPO_PATH}/deploy:latest

  # ---------------------------------------------------- Execution -----------------------------------------------------

  dev:
    image: ${REGISTRY_HOST}/${REGISTRY_REPO_PATH}/builder-linux-clang-dev:latest
    container_name: "Linux_GCC_and_Clang_dev_env"
    ports:
      - "3022:22"
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: docker/docker-entrypoint-dev.sh

  dev-windows:
    image: ${REGISTRY_HOST}/${REGISTRY_REPO_PATH}/builder-windows-mingw-dev:latest
    container_name: "Windows_mingw_dev_env"
    ports:
      - "3022:22"
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: docker/docker-entrypoint-dev.sh

  ci:
    image: ${REGISTRY_HOST}/${REGISTRY_REPO_PATH}/builder-linux-clang-ci:latest
    container_name: "Linux_GCC_and_Clang_ci_env"
    tty: true
    stdin_open: true
    volumes:
      - .:/app