FROM ubuntu:22.04

WORKDIR /mnt

ENV MINGW=/mingw

ARG CMAKE_VERSION
ARG GCC_VERSION
ARG PKG_CONFIG_VERSION
ARG BINUTILS_VERSION
ARG MINGW_VERSION
ARG SDL_VERSION
ARG LEPTONICA_VERSION
ARG TESSERACT_VERSION
ARG OPENCV_VERSION
ARG NLOHMANN_JSON_VERSION
ARG QUILL_VERSION
ARG GOOGLETEST_VERSION
ARG MAX_CPU_CORES

SHELL [ "/bin/bash", "-c" ]

# @todo mingw from https://github.com/mingw-w64/mingw-w64 ?
RUN set -ex \
    \
    # Global compilation lib tools
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get upgrade --no-install-recommends -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
        ca-certificates \
        gcc \
        g++ \
        zlib1g-dev \
        libssl-dev \
        libgmp-dev \
        libmpfr-dev \
        libmpc-dev \
        libisl-dev \
        libssl3 \
        libgmp10 \
        libmpfr6 \
        libmpc3 \
        libisl23 \
        xz-utils \
        ninja-build \
        texinfo \
        meson \
        gnupg \
        bzip2 \
        patch \
        gperf \
        bison \
        file \
        flex \
        make \
        yasm \
        wget \
        zip \
        git \
    \
    # Download source code for PKG_CONFIG, CMAKE, BINUTILS, MINGW, GCC and NASM
    && wget -q https://pkg-config.freedesktop.org/releases/pkg-config-${PKG_CONFIG_VERSION}.tar.gz -O - | tar -xz \
    && wget -q https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz -O - | tar -xz \
    && wget -q https://ftp.gnu.org/gnu/binutils/binutils-${BINUTILS_VERSION}.tar.xz -O - | tar -xJ \
    && wget -q https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v${MINGW_VERSION}.tar.bz2 -O - | tar -xj \
    && wget -q https://ftp.gnu.org/gnu/gcc/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.xz -O - | tar -xJ \
    \
    && mkdir -p ${MINGW}/include ${MINGW}/lib/pkgconfig \
    && chmod 0777 -R /mnt ${MINGW} \
    \
    # Install PKG_CONFIG
    && cd pkg-config-${PKG_CONFIG_VERSION} \
    && ./configure \
        --prefix=/usr/local \
        --with-pc-path=${MINGW}/lib/pkgconfig \
        --with-internal-glib \
        --disable-shared \
        --disable-nls \
    && make -j ${MAX_CPU_CORES} \
    && make install \
    && cd .. \
    \
    # Install CMAKE
    && cd cmake-${CMAKE_VERSION} \
    && ./configure \
        --prefix=/usr/local \
        --parallel=${MAX_CPU_CORES} \
    && make -j ${MAX_CPU_CORES} \
    && make install \
    && cd .. \
    \
    # Install BINUTILS
    && cd binutils-${BINUTILS_VERSION} \
    && ./configure \
        --prefix=/usr/local \
        --target=x86_64-w64-mingw32 \
        --disable-shared \
        --enable-static \
        --disable-lto \
        --disable-plugins \
        --disable-multilib \
        --disable-nls \
        --disable-werror \
        --with-system-zlib \
    && make -j ${MAX_CPU_CORES} \
    && make install \
    && cd .. \
    \
    # Install MINGW headers
    && mkdir mingw-w64 \
    && cd mingw-w64 \
    && ../mingw-w64-v${MINGW_VERSION}/mingw-w64-headers/configure \
        --prefix=/usr/local/x86_64-w64-mingw32 \
        --host=x86_64-w64-mingw32 \
        --enable-sdk=all \
    && make install \
    && cd .. \
    \
    # Install GCC
    && mkdir gcc \
    && cd gcc \
    && ../gcc-${GCC_VERSION}/configure \
        --prefix=/usr/local \
        --target=x86_64-w64-mingw32 \
        --enable-languages=c,c++ \
        --disable-shared \
        --enable-static \
        --enable-threads=posix \
        --with-system-zlib \
        --enable-libgomp \
        --enable-libatomic \
        --enable-graphite \
        --disable-libstdcxx-pch \
        --disable-libstdcxx-debug \
        --disable-multilib \
        --disable-lto \
        --disable-nls \
        --disable-werror \
    && make -j ${MAX_CPU_CORES} all-gcc \
    && make install-gcc \
    && cd .. \
    \
    # Install MINGW crt
    && cd mingw-w64 \
    && ../mingw-w64-v${MINGW_VERSION}/mingw-w64-crt/configure \
        --prefix=/usr/local/x86_64-w64-mingw32 \
        --host=x86_64-w64-mingw32 \
        --enable-wildcard \
        --disable-lib32 \
        --enable-lib64 \
    && (make -j ${MAX_CPU_CORES} || make -j ${MAX_CPU_CORES} || make -j ${MAX_CPU_CORES} || make -j ${MAX_CPU_CORES}) \
    && make install \
    && cd .. \
    \
    # Install MINGW winpthreads
    && cd mingw-w64 \
    && ../mingw-w64-v${MINGW_VERSION}/mingw-w64-libraries/winpthreads/configure \
        --prefix=/usr/local/x86_64-w64-mingw32 \
        --host=x86_64-w64-mingw32 \
        --enable-static \
        --disable-shared \
    && make -j ${MAX_CPU_CORES} \
    && make install \
    && cd .. \
    \
    # Recompile GCC
    && cd gcc \
    && make -j ${MAX_CPU_CORES} \
    && make install \
    && cd .. \
    \
    # Clean up downloaded source files
    && rm -r pkg-config-${PKG_CONFIG_VERSION} \
    && rm -r cmake-${CMAKE_VERSION} \
    && rm -r binutils-${BINUTILS_VERSION} \
    && rm -r mingw-w64 mingw-w64-v${MINGW_VERSION} \
    && rm -r gcc gcc-${GCC_VERSION}

ENV INSTALL_PREFIX=/usr/local/x86_64-w64-mingw32
ENV CMAKE_TOOLCHAIN=/tmp/mingw-w64-x86_64.cmake

# Copy cmake tolchain fro windows cross compiling
COPY cmake/mingw-w64-x86_64.cmake /tmp
# Define default compiler as mingw
RUN export CC="/usr/local/bin/x86_64-w64-mingw32-gcc" && export CXX="/usr/local/bin/x86_64-w64-mingw32-g++"

# Install SDL with the given SDL_VERSION version from https://github.com/libsdl-org/SDL
RUN apt-get update && apt-get install -y libgtk-3-dev && \
    wget https://github.com/libsdl-org/SDL/archive/refs/tags/release-${SDL_VERSION}.tar.gz \
    -q -O /tmp/sdl-${SDL_VERSION}.tar.gz && \
    cd /tmp && tar -xvzf sdl-${SDL_VERSION}.tar.gz && cd SDL-release-${SDL_VERSION} && \
    cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} -DBUILD_SHARED_LIBS=ON --install-prefix ${INSTALL_PREFIX} && \
    cmake --build build -j ${MAX_CPU_CORES} && cmake --install build && \
    rm -rf /tmp/sdl-${SDL_VERSION}.tar.gz /tmp/SDL-release-${SDL_VERSION}

# Install leptonica with the given LEPTONICA_VERSION from https://github.com/DanBloomberg/leptonica
RUN wget https://github.com/DanBloomberg/leptonica/archive/refs/tags/${LEPTONICA_VERSION}.tar.gz \
    -q -O /tmp/leptonica-${LEPTONICA_VERSION}.tar.gz && \
    cd /tmp && tar -xvzf leptonica-${LEPTONICA_VERSION}.tar.gz && cd leptonica-${LEPTONICA_VERSION} && \
    cmake -S . -B build --install-prefix ${INSTALL_PREFIX} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} \
    -DCMAKE_BUILD_TYPE=Release -DBUILD_PROG=OFF -DSW_BUILD=OFF -DBUILD_SHARED_LIBS=ON && \
    cmake --build build -j ${MAX_CPU_CORES} && cmake --install build && \
    rm -rf /tmp/leptonica-${LEPTONICA_VERSION}.tar.gz /tmp/leptonica-${LEPTONICA_VERSION}

# Install tesseract with the given TESSERACT_VERSION from https://github.com/tesseract-ocr/tesseract
RUN wget https://github.com/tesseract-ocr/tesseract/archive/refs/tags/${TESSERACT_VERSION}.tar.gz \
    -q -O /tmp/tesseract-${TESSERACT_VERSION}.tar.gz && \
    cd /tmp && tar -xvzf tesseract-${TESSERACT_VERSION}.tar.gz && cd tesseract-${TESSERACT_VERSION} && \
    # @fixme include an extra libraries search directory with a CMake flag instead of hacking the CMakeLists.txt
    sed -i 's/LIB_Ws2_32 Ws2_32/LIB_Ws2_32 \/usr\/local\/x86_64-w64-mingw32\/lib\/libws2_32\.a/g' CMakeLists.txt && \
    mkdir build && cd build && cmake .. --install-prefix ${INSTALL_PREFIX} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} \
    -DCMAKE_BUILD_TYPE=Release -DDISABLED_LEGACY_ENGINE=ON -DSW_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF -DGRAPHICS_DISABLED=ON \
    -DENABLE_LTO=ON -DBUILD_SHARED_LIBS=ON -DDISABLE_ARCHIVE=ON -DDISABLE_CURL=ON && \
    make -j ${MAX_CPU_CORES} && make install && \
    rm -rf /tmp/tesseract-${TESSERACT_VERSION}.tar.gz /tmp/tesseract-${TESSERACT_VERSION}

# Get tesseract latin trained data for tesseract
ENV TESSDATA_PREFIX "/usr/local/share/tessdata"
# tessdata_fast fail on detecting Queen 'Q' on Winamax OCR
RUN mkdir -p ${TESSDATA_PREFIX} && \
    wget https://github.com/tesseract-ocr/tessdata_best/raw/main/eng.traineddata -q -O ${TESSDATA_PREFIX}/eng.traineddata

# Install OpenCV with the given OPENCV_VERSION from https://github.com/opencv/opencv
RUN apt-get install -y libgtkglext1-dev libopenjp2-7-dev libgtk-3-dev libcanberra-gtk3-module && \
    wget https://github.com/opencv/opencv/archive/refs/tags/${OPENCV_VERSION}.tar.gz -q -O /tmp/opencv-${OPENCV_VERSION}.tar.gz && \
    wget https://github.com/opencv/opencv_contrib/archive/refs/tags/${OPENCV_VERSION}.tar.gz \
    -q -O /tmp/opencv_contrib-${OPENCV_VERSION}.tar.gz && \
    cd /tmp && tar -xvzf opencv-${OPENCV_VERSION}.tar.gz && tar -xvzf opencv_contrib-${OPENCV_VERSION}.tar.gz && \
    cd opencv-${OPENCV_VERSION} && mkdir opencv_build && cd opencv_build && \
    cmake .. --install-prefix ${INSTALL_PREFIX} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} -DBUILD_LIST="core,highgui,imgcodecs,text" \
    -DOPENCV_EXTRA_MODULES_PATH="../../opencv_contrib-${OPENCV_VERSION}/modules" -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF \
    -DWITH_OPENCL=OFF -DENABLE_CXX11=ON -DBUILD_SHARED_LIBS=ON && make -j ${MAX_CPU_CORES} && make install && \
    rm -rf /tmp/opencv-${OPENCV_VERSION}.tar.gz /tmp/opencv-${OPENCV_VERSION} /tmp/opencv_contrib-${OPENCV_VERSION}.tar.gz \
    /tmp/opencv_contrib-${OPENCV_VERSION}

# Install nlohmann_json with the given NLOHMANN_JSON_VERSION version from https://github.com/nlohmann/json
RUN wget https://github.com/nlohmann/json/archive/refs/tags/v${NLOHMANN_JSON_VERSION}.tar.gz \
    -q -O /tmp/json-${NLOHMANN_JSON_VERSION}.tar.gz && \
    cd /tmp && ls && tar -xvzf json-${NLOHMANN_JSON_VERSION}.tar.gz && cd json-${NLOHMANN_JSON_VERSION} && \
    mkdir build && cd build && cmake .. --install-prefix ${INSTALL_PREFIX} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} \
    ${INSTALL_PREFIX} -DBUILD_SHARED_LIBS=ON && make -j ${MAX_CPU_CORES} && \
    make install && \
    rm -rf /tmp/json-${NLOHMANN_JSON_VERSION}.tar.gz /tmp/json-${NLOHMANN_JSON_VERSION}

# Install quill with the given QUILL_VERSION version from https://github.com/odygrd/quill
RUN wget https://github.com/odygrd/quill/archive/refs/tags/v${QUILL_VERSION}.tar.gz -q -O /tmp/quill-${QUILL_VERSION}.tar.gz && \
    cd /tmp && ls && tar -xvzf quill-${QUILL_VERSION}.tar.gz && cd quill-${QUILL_VERSION} && \
    mkdir build && cd build && cmake .. --install-prefix ${INSTALL_PREFIX} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} \
    -DBUILD_SHARED_LIBS=ON && make -j ${MAX_CPU_CORES} && \
    make install && \
    rm -rf /tmp/quill-${QUILL_VERSION}.tar.gz /tmp/quill-${QUILL_VERSION}

# Install googleTest with the given GOOGLETEST_VERSION version from https://github.com/google/googletest
RUN wget https://github.com/google/googletest/archive/refs/tags/v${GOOGLETEST_VERSION}.tar.gz \
    -q -O /tmp/googletest-${GOOGLETEST_VERSION}.tar.gz && \
    cd /tmp && tar -xvzf googletest-${GOOGLETEST_VERSION}.tar.gz && cd googletest-${GOOGLETEST_VERSION} && \
    cmake . --install-prefix ${INSTALL_PREFIX} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} -DBUILD_SHARED_LIBS=ON && \
    make -j ${MAX_CPU_CORES} && make install && \
    rm -rf /tmp/googletest-${GOOGLETEST_VERSION}.tar.gz /tmp/googletest-${GOOGLETEST_VERSION}

# Clean ubuntu apt packages
RUN apt-get remove --purge -y file gcc g++ zlib1g-dev libssl-dev libgmp-dev libmpfr-dev libmpc-dev libisl-dev gnupg \
    && apt-get autoremove --purge -y \
    && apt-get clean

WORKDIR /app

CMD ["/bin/bash"]
