ARG GCC_VERSION

FROM gcc:${GCC_VERSION}

ARG CMAKE_VERSION

 # Define the number of parallel CPU core to execute MAKE commands
RUN export makeCores=$(($(nproc)-1))

# Install CMake with the given CMAKE_VERSION version from https://github.com/Kitware/CMake
RUN wget https://gitlab.kitware.com/cmake/cmake/-/archive/v${CMAKE_VERSION}/cmake-v${CMAKE_VERSION}.tar.gz \
    -q -O /tmp/cmake-v${CMAKE_VERSION}.tar.gz && \
    cd /tmp && tar -xvzf cmake-v${CMAKE_VERSION}.tar.gz && cd cmake-v${CMAKE_VERSION} && \
    ./bootstrap --parallel=${makeCores} -- -DCMAKE_USE_OPENSSL=OFF && make -j ${makeCores} && make install && \
    rm -rf /tmp/cmake-v${CMAKE_VERSION}.tar.gz /tmp/cmake-v${CMAKE_VERSION}

# Install Python with PIP and Conan packages manager
RUN apt-get update && apt-get install python3 \
    && wget https://bootstrap.pypa.io/get-pip.py \
    && python3 get-pip.py \
    && pip3 install conan \
    && rm -rf get-pip.py

WORKDIR /app

CMD ["/bin/bash"]
